"""empty message

Revision ID: 4ad17965ef40
Revises: 1b4504c42601
Create Date: 2019-04-27 22:14:11.304099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad17965ef40'
down_revision = '1b4504c42601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('follows_user_id_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_follower_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'caption',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'created_on',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('posts', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'biography',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'joined_on',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'joined_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'biography',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'created_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('posts', 'caption',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'])
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_follower_id_fkey', 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key('follows_user_id_fkey', 'follows', 'users', ['user_id'], ['id'])
    op.alter_column('follows', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
